
export const cardList = [
  {
    cardName: "burger",
    src: require(`./assets/burger.jpg`),
    id: 1,
    matchFound: false,
  },
  {
    cardName: "french fries",
    src: require(`./assets/french fries.jpg`),
    id: 2,
    matchFound: false,
  },
  {
    cardName: "hotdog",
    src: require(`./assets/hotdog.jpg`),
    id: 3,
    matchFound: false,
  },
  {
    cardName: "ice cream",
    src: require(`./assets/ice_cream.jpg`),
    id: 4,
    matchFound: false,
  },
  {
    cardName: "pancakes",
    src: require(`./assets/pancakes.jpg`),
    id: 5,
    matchFound: false,
  },
  {
    card: "veggies",
    src: require(`./assets/veggies.jpg`),
    id: 6,
    matchFound: false,
  },
  {
    cardName: "pizza",
    src: require(`./assets/pizza.jpg`),
    id: 7,
    matchFound: false,
  },
  {
    cardName: "ramen",
    src: require(`./assets/ramen.jpg`),
    id: 8,
    matchFound: false,
  },
  {
    cardName: "takoyaki",
    src: require(`./assets/takoyaki.jpg`),
    id: 9,
    matchFound: false,
  },
  {
    cardName: "onigiri",
    src: require(`./assets/onigiri.jpg`),
    id: 10,
    matchFound: false,
  },
  {
    cardName: "smores",
    src: require(`./assets/smores.jpg`),
    id: 11,
    matchFound: false,
  },
  {
    cardName: "breakfast",
    src: require(`./assets/breakfast.jpg`),
    id: 12,
    matchFound: false,
  },
  {
    card: "boba",
    src: require(`./assets/boba.jpg`),
    id: 13,
    matchFound: false,
  },
  {
    cardName: "donut",
    src: require(`./assets/donut.jpg`),
    id: 14,
    matchFound: false,
  },
  {
    cardName: "coffee_toast",
    src: require(`./assets/coffee_toast.jpg`),
    id: 15,
    matchFound: false,
  },
  {
    cardName: "shiba_sushi",
    src: require(`./assets/shiba_sushi.jpg`),
    id: 16,
    matchFound: false,
  },
  {
    cardName: "sushi",
    src: require(`./assets/sushi.jpg`),
    id: 17,
    matchFound: false,
  },
  {
    cardName: "tempura",
    src: require(`./assets/tempura.jpg`),
    id: 18,
    matchFound: false,
  },
  {
    cardName: "bento",
    src: require(`./assets/bento.jpg`),
    id: 19,
    matchFound: false,
  },
  {
    cardName: "gyoza",
    src: require(`./assets/gyoza.jpg`),
    id: 19,
    matchFound: false,
  },
  {
    cardName: "burrito",
    src: require(`./assets/burrito.jpg`),
    id: 20,
    matchFound: false,
  },
  {
    cardName: "sushi2",
    src: require(`./assets/sushi2.jpg`),
    id: 21,
    matchFound: false,
  },
  {
    cardName: "chips_salsa",
    src: require(`./assets/chips_salsa.jpg`),
    id: 22,
    matchFound: false,
  },
  {
    cardName: "taco",
    src: require(`./assets/taco.jpg`),
    id: 23,
    matchFound: false,
  },
  {
    cardName: "cake",
    src: require(`./assets/cake.jpg`),
    id: 24,
    matchFound: false,
  },
  {
    cardName: "dango",
    src: require(`./assets/dango.jpg`),
    id: 25,
    matchFound: false,
  },
  {
    cardName: "milk-cookies",
    src: require(`./assets/milk-cookies.jpg`),
    id: 26,
    matchFound: false,
  },
  {
    cardName: "pineapple",
    src: require(`./assets/pineapple.jpg`),
    id: 27,
    matchFound: false,
  },
  {
    cardName: "fruit",
    src: require(`./assets/fruit.jpg`),
    id: 28,
    matchFound: false,
  },
  {
    cardName: "burger2",
    src: require(`./assets/burger2.jpg`),
    id: 29,
    matchFound: false,
  },
  {
    cardName: "super-sausage",
    src: require(`./assets/super-sausage.jpg`),
    id: 30,
    matchFound: false,
  },
  {
    cardName: "happy-meal",
    src: require(`./assets/happy-meal.jpg`),
    id: 31,
    matchFound: false,
  },
  {
    cardName: "cotton-candy",
    src: require(`./assets/cotton-candy.jpg`),
    id: 32,
    matchFound: false,
  },
];